In [1]:
import numpy as np
from numpy.testing import assert_almost_equal
from ppr.ga import GASolver, get_shortest_path_ga, LazyGASolver
from ppr.robot import Robot_2P3R
from ppr.path import TolerancedNumber, TrajectoryPt
from ppr.geometry import Rectangle
from ppr.util import VirtualJointSolutions

In [2]:
# create trajectory point
x = TolerancedNumber(2, 1, 3, samples=3)
y = TolerancedNumber(2.5, 2, 3, samples=4)
tp = TrajectoryPt([x, y, 0])

# create robot and collision scene
robot1 = Robot_2P3R([1, 1, 2, 1.5, 0.5])
sc1 = [Rectangle(2, 1, 0.5, 0.5, 0)]

# create the object
Qv = [VirtualJointSolutions(robot1, tp, sc1),
      VirtualJointSolutions(robot1, tp, sc1)]

ls = LazyGASolver(Qv)

In [3]:
ls.create_population()

([array([ 64, 540]),
  array([346, 439]),
  array([288, 583]),
  array([490, 114]),
  array([107,  30]),
  array([572, 572]),
  array([327, 424]),
  array([399, 384]),
  array([508, 238]),
  array([421, 500]),
  array([586, 525]),
  array([378,   7]),
  array([421, 446]),
  array([513,  84]),
  array([198, 467]),
  array([356, 154]),
  array([281, 523]),
  array([547, 550]),
  array([255, 165]),
  array([353, 266]),
  array([333, 240]),
  array([465, 417]),
  array([467, 429]),
  array([524, 594]),
  array([540, 587]),
  array([120, 114]),
  array([493, 564]),
  array([574, 534]),
  array([118, 545]),
  array([  3, 142])],
 [array([[ 0.        ,  0.25      ,  0.4820183 ,  1.44430185, -1.92632015],
         [ 0.        ,  1.        ,  2.5717444 , -1.91063324, -0.66111116]]),
  array([[ 0.75      ,  0.        ,  1.56029679, -1.39277417, -0.16752262],
         [ 0.25      ,  0.5       ,  1.78586963, -1.47225731, -0.31361232]]),
  array([[ 1.        ,  1.        ,  1.19896206,  2.55590711,